#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Oct 06 16:48:15 IST 2017
apiSecret=6075b29c8642c224994fb3f0628aa5e7dabfd10f9491dfb804bee6f3ae6c7c9b
